"""Schemas for constrained analysis plans, evidence, and explanations."""

from typing import Any, Literal

from pydantic import BaseModel, ConfigDict, Field, model_validator

Operation = Literal[
    "describe",
    "groupby_aggregate",
    "top_k",
    "correlation",
    "time_trend",
    "missing_values",
    "outlier_iqr",
]
Aggregation = Literal["sum", "mean", "count", "min", "max", "median"]
SortOrder = Literal["asc", "desc"]
ChartType = Literal["bar", "line", "scatter", "histogram", "box"]


class AnalysisPlan(BaseModel):
    """A single safe operation selected by Hy3 and executed locally."""

    model_config = ConfigDict(
        extra="forbid",
        json_schema_extra={
            "required": [
                "operation",
                "target_columns",
                "group_by",
                "aggregation",
                "sort_order",
                "limit",
                "time_column",
                "rationale",
            ]
        },
    )

    operation: Operation
    target_columns: list[str] = Field(default_factory=list, max_length=20)
    group_by: list[str] = Field(default_factory=list, max_length=5)
    aggregation: Aggregation | None = None
    sort_order: SortOrder = "desc"
    limit: int = Field(default=20, ge=1, le=100)
    time_column: str | None = None
    rationale: str = Field(min_length=1, max_length=1000)

    @model_validator(mode="after")
    def validate_operation_arguments(self) -> "AnalysisPlan":
        if self.operation == "groupby_aggregate":
            if not self.group_by or not self.target_columns or self.aggregation is None:
                raise ValueError(
                    "groupby_aggregate requires group_by, target_columns, and aggregation"
                )
        elif self.operation == "top_k" and not self.target_columns:
            raise ValueError("top_k requires at least one target column")
        elif self.operation == "correlation" and len(self.target_columns) < 2:
            raise ValueError("correlation requires at least two target columns")
        elif self.operation == "time_trend":
            if self.time_column is None or not self.target_columns or self.aggregation is None:
                raise ValueError("time_trend requires time_column, target_columns, and aggregation")
        elif self.operation == "outlier_iqr" and not self.target_columns:
            raise ValueError("outlier_iqr requires at least one target column")
        return self


class AnalysisEvidence(BaseModel):
    """Bounded deterministic evidence produced by the local executor."""

    operation: Operation
    summary: str
    records: list[dict[str, Any]] = Field(default_factory=list, max_length=100)
    metrics: dict[str, Any] = Field(default_factory=dict)
    warnings: list[str] = Field(default_factory=list)


class EvidenceInterpretation(BaseModel):
    """Hy3 explanation grounded only in deterministic evidence."""

    conclusion: str = Field(min_length=1, max_length=4000)
    evidence_references: list[str] = Field(default_factory=list, max_length=20)
    limitations: list[str] = Field(default_factory=list, max_length=20)


class ChartSuggestion(BaseModel):
    """One non-rendering visualization recommendation."""

    model_config = ConfigDict(extra="forbid")

    chart_type: ChartType
    title: str = Field(min_length=1, max_length=200)
    x: str | None = None
    y: str | None = None
    color: str | None = None
    aggregation: Aggregation | None = None
    rationale: str = Field(min_length=1, max_length=1000)


class VisualizationSuggestions(BaseModel):
    """Bounded structured response generated by Hy3."""

    suggestions: list[ChartSuggestion] = Field(min_length=1, max_length=5)


def validate_visualization_columns(result: VisualizationSuggestions, columns: list[str]) -> None:
    """Reject invented chart encodings before returning suggestions."""
    known = set(columns)
    unknown = sorted(
        {
            value
            for suggestion in result.suggestions
            for value in (suggestion.x, suggestion.y, suggestion.color)
            if value is not None and value not in known
        }
    )
    if unknown:
        raise ValueError(f"unknown visualization columns: {', '.join(unknown)}")


def validate_plan_columns(plan: AnalysisPlan, columns: list[str]) -> None:
    """Reject invented or ambiguous column references before execution."""
    known = set(columns)
    referenced = set(plan.target_columns) | set(plan.group_by)
    if plan.time_column is not None:
        referenced.add(plan.time_column)
    unknown = sorted(referenced - known)
    if unknown:
        raise ValueError(f"unknown columns: {', '.join(unknown)}")
